export const SIGNUP_LOADING = 'SIGNUP_LOADING'; 
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE'; 
export const SIGNUP_ERROR = 'SIGNUP_ERROR'; 
export const SET_AUTHENTICATION = 'SET_AUTHENTICATON';
export const SET_LOG_OUT = 'SET_LOG_OUT'
export const SET_ERROR = 'SET_ERROR';